import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/login/user.dart';
import '../services/session_manager.dart';
import 'profile_provider.dart';

class AuthNotifier extends AsyncNotifier<User?> {
  @override
  Future<User?> build() async {
    final userId = await SessionManager.getSavedUserId();
    final username = await SessionManager.getSavedUsername();

    if (userId != null && username != null) {
      await ref.read(profileProvider.notifier).load(userId);
      return User(id: userId, username: username, password: '');
    }
    return null;
  }

  Future<void> login(User user) async {
    await SessionManager.saveSession(user.id!, user.username);
    await ref.read(profileProvider.notifier).load(user.id!);
    state = AsyncData(user);
  }

  Future<void> logout() async {
    await SessionManager.clearSession();
    ref.read(profileProvider.notifier).clear();
    state = const AsyncData(null);
  }

  //updates the username in state and session storage.
  //Call this after DatabaseHelper.editUsername succeeds.
  Future<void> updateUsername(String newName) async {
    final currentUser = state.value;
    if (currentUser == null) return;
    state = AsyncData(
      User(id: currentUser.id, username: newName, password: ''),
    );
    await SessionManager.saveSession(currentUser.id!, newName);
  }

  // hash pass is generated by [DatabaseHelper.editPassword]
  Future<void> updatePassword() async {
    final currentUser = state.value;
    if (currentUser == null) return;
    state = AsyncData(
      User(id: currentUser.id, username: currentUser.username, password: ''),
    );
  }
}

final authProvider = AsyncNotifierProvider<AuthNotifier, User?>(
  AuthNotifier.new,
);
