// auth_provider.dart

// Manages the current logged-in user in the app.
//
// State type: User? (At the build() stage)
// return
//   null - nobody is logged in
//   User - an account is active
//
// Flow:
//   build() - called once, tries to restore a saved session from SharedPrefs
//   login()- saves session and loads profile picture
//   logout() clears session and wipes profile state
//   updateUsername()- called when user changed their username
//   updatePassword()- called when user changes their pass

//SessionManager  — reads/writes userId & username to prefs (SharedPreferences)
//profileProvider — makes sure the user uses his/her own profile pic

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/login/user.dart';
import '../services/session_manager.dart';
import 'profile_provider.dart';

class AuthNotifier extends AsyncNotifier<User?> {
  @override
  Future<User?> build() async {
    final userId = await SessionManager.getSavedUserId();
    final username = await SessionManager.getSavedUsername();

    if (userId != null && username != null) {
      await ref.read(profileProvider.notifier).load(userId);
      return User(id: userId, username: username, password: '');
    }
    return null;
  }

  // Called after login or account creation and loads the user profile picture
  Future<void> login(User user) async {
    await SessionManager.saveSession(user.id!, user.username);
    await ref.read(profileProvider.notifier).load(user.id!);
    state = AsyncData(user);
  }

  //clears the session from SharedPrefs and wipes the profile pic then redirect to the login screen once
  Future<void> logout() async {
    await SessionManager.clearSession();
    ref.read(profileProvider.notifier).clear();
    state = const AsyncData(null);
  }

  //updates the username in state and session storage.
  //call this after DatabaseHelper.editUsername succeeds.
  Future<void> updateUsername(String newName) async {
    final currentUser = state.value;
    if (currentUser == null) return;
    state = AsyncData(
      User(id: currentUser.id, username: newName, password: ''),
    );
    await SessionManager.saveSession(currentUser.id!, newName);
  }

  // hash pass is generated by DatabaseHelper.editPassword and stored in the database
  Future<void> updatePassword() async {
    final currentUser = state.value;
    if (currentUser == null) return;
    state = AsyncData(
      User(id: currentUser.id, username: currentUser.username, password: ''),
    );
  }
}

final authProvider = AsyncNotifierProvider<AuthNotifier, User?>(
  AuthNotifier.new,
);
